name: uni_sphere_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
#!----------------------------dependencies------------------------------------!# 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  dio_refresh_bot: ^2.2.1
  cached_network_image: ^3.2.3
  freezed: ^3.0.6
  reactive_forms: ^18.0.0
  intl: ^0.19.0  
  provider: ^6.1.2
  freezed_annotation: ^3.0.0
  beamer: ^1.7.0
  google_fonts: ^6.2.1
  flutter_gen: ^5.10.0
  flutter_svg: ^2.0.17 
  flutter_bloc: ^9.1.0   
  easy_localization: ^3.0.7+1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  fpdart: ^1.1.1 #this the same as dart z but newly support 
  flutter_secure_storage: ^9.2.4
  # jwt_decoder: ^2.0.1
  # flutter_timezone: ^4.1.0
  internet_connection_checker: ^3.0.1
  package_info_plus: ^8.3.0
  flutter_spinkit: ^5.2.1
  lottie: ^3.2.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  device_frame_plus: ^1.4.0
  easy_localization_loader: ^2.0.2
#!---------------------------dev_dependencies-------------------------------------!# 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0 
  json_serializable: ^6.9.0

#!----------------------------flutter-needs------------------------------------!# 

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#!---------------------------assets-------------------------------------!# 
  assets:
    - assets/images/
    - assets/icons/
    - assets/l10n/

#!---------------------------fonts-------------------------------------!# 

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

